/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 trampoline.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/trampoline.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cylinder001_Curve.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/trampoline.glb')
