/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 checker.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({rotation,...props}) {
  const { nodes, materials } = useGLTF('./models/checker.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.Checkered} rotation={rotation} receiveShadow/>
    </group>
  )
}

useGLTF.preload('/checker.glb')
